language: cpp
compiler:
    - gcc
    - clang

before_install:
 - if [ "$CXX" == "g++" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test; fi
 - if [ "$CXX" == "g++" ]; then sudo apt-get update; fi
 - if [ "$CXX" == "g++" ]; then sudo apt-get install gcc-5 g++-5; fi
 - if [ "$CXX" == "g++" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5; fi
 - if [ "$CXX" == "clang++" ]; then CC="clang"; fi
 - echo $CXX
 - echo $CC
 - $CC --version
 - $CXX --version
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - echo $CC
 - export QtMkspec=$CC

install:
 - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
 - sudo apt-get install qt5-default qttools5-dev-tools
 - sudo apt-get install qtmultimedia5-dev libqt5multimediawidgets5 libqt5multimedia5-plugins libqt5multimedia5
 - sudo apt-get install libboost-all-dev
 - sudo apt-get install libc++-dev
 - git clone https://github.com/miloyip/rapidjson.git ~/rapidjson
 - cd ~/rapidjson
 - mkdir build
 - cd build
 - cmake ..
 - sudo make install

script:
 - echo $CC
 - echo $QtMkspec
 - $QtMkspec --version
 - qmake -qt=qt5 -v
 - qmake -qt=qt5 -spec linux-$QtMkspec
 - make 
